language: ruby
rvm:
- 2.3.1
bundler_args: "--without development --deployment"
cache: bundler
before_script:
- bundle exec rake db:create
- bundle exec rake db:migrate
- gem install brakeman
script:
- bundle exec rake test
- brakeman
- bundle exec bundle-audit check --update
notifications:
  email:
    on_success: never
    on_failure: always
  slack:
    secure: WSi2+hSja+1qWIqFZG99oqU4LkbgL08ig43ARrnM7xVrnHDcwfGWOOb5WATOHkewL599y+/2t5MAF3tw54JzuHPU9DH5ZDxEmQHUfbdRPMBkP1BJP5vYp9SchPp+nqp5r6bsPDwS1U5dPqEMf7s28VqYegNMNbSxKTNkOXyy31m6OScZwKC/XGt8RlHUEWbicK2SZrD0ZtVuLb0qlZ+3MJCgsb00cdtG2TSfB+u1LQjrH/l9shmoJGwyWoVmir8MY1GjtrvO/POAifrpAK42MqVzgdX1Bc+uu1/dB35Jm5NTMXgQv0emy4KTy4NnMPYqpatAsUJd4sfUMNtuwrTkyo75JsnmoU/gAPOEgPGKjhIzOckXbvHTU9K/FdFoPPYCUVKBmHKRMIGHGzhMgU/tZz7kU2WuylmpzYD6vA+g6AScZE9K1YjIYZC6u7pbxlwGdX89o0t/7xDu8pO6AHeAiipEpZBDwiv3aDSDR+2mX1X6jHP95zKvixtheC8zKkn1iVGBI7Dpg05/Kt0yA6rpNkxwYOTrlrUVpWkl/KSkQk5Se0q1Bg40JdHtsCOyiyaLZVUVvlnrHMKWRd4vfheJ2xfrHo9b4tWxZS/y/ZVah0gEmNNSAIEcKDUpFpc8l+2Q2NhmnHamXaT1VhCc/Bs+O1B7u3Q4ifRbtnXoHyelqes=
