# Use the README file as a reference to customize settings.

Drinking:
  fields:
    default: festival_id, drinker_id, restaurant_id, sake_id, sake_temperature_id
    form: festival_id, drinker_id, restaurant_id, sake_id, sake_temperature_id
  relationships: vote
  application: Application
