# Use the README file as a reference to customize settings.

Restaurant:
  fields:
    default: name, latitude, longitude, capacity, congestion_degree
    form: name, latitude, longitude, capacity, congestion_degree
  relationships: 
  application: Application
