# Use the README file as a reference to customize settings.

RestaurantParticipation:
  fields:
    default: festival_id, restaurant_id
    form: festival_id, restaurant_id
  relationships: 
  application: Application
